FROM eclipse-temurin:21-jdk-jammy

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY target/emergency-service-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 9093

ENTRYPOINT ["java", "-jar", "app.jar"]
